SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND (I.SEX_UPON_INTAKE = 'Intact Male' OR I.SEX_UPON_INTAKE = 'Intact FeMale') AND (O.SEX_UPON_OUTCOME = 'Spayed Female' OR O.SEX_UPON_OUTCOME = 'Neutered Male')
ORDER BY ANIMAL_ID;