-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN
    (SELECT O.ANIMAL_ID
     FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
     WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY ANIMAL_ID;